GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI2NTUzMDIsImV4cCI6MTczMjY1NTM2Mn0.-uKoaTjY-NvPR6bT9SpmKXRA1bf_OHIm7xchxz3naZY

###ping route
GET http://localhost:3000/api/ping


###register route
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName":"Arselene",
    "lastName":"Meghlaoui",
    "username":"exodia",
    "email":"arselene.test10010@gmail.com",
    "password":"12345678"
}

###verify-credentials route
POST  http://localhost:3000/auth/validate-credentials
Content-Type: application/json

{
    "email":"arselene.test10010@gmail.com",
    "password":"12345678"
}


###verify-pins route
POST  http://localhost:3000/auth/validate-pins
Content-Type: application/json

{
    "userId":"676aecc3cfa5a5c5fe6b7f1e",
    "pin1":"6077",
    "pin2":"9625"
}


###verify-locations route
POST  http://localhost:3000/auth/validate-location
Content-Type: application/json

{
    "latitude":"36.815099",
    "longitude":"7.716793"
}


###refresh-token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mjg2ODk5MzUsImV4cCI6MTc2MDI0NzUzNSwiYXVkIjoiNjcwOTYwM2RiYTQwN2ZkMWVhMjdiZTFlIiwiaXNzIjoiaWRrLmNvbSJ9.bLctubDocxe1WzNiafZr5dZqWhubiVoSiTYWiH0z6Ak"
}


###logout route
POST  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI1NzQzMTQsImV4cCI6MTczMzE3OTExNH0.3W1mD95EYpW4WrFT3jliYmKxBU9Ud8pZCKB71Q9gtFM"
}


###check-refresh-token route
POST http://localhost:3000/auth/check-refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI2NTc1NjcsImV4cCI6MTczMzI2MjM2N30.MAjkUOv799co5TLSQ0Bah8UqQ4CSPajvcUyLS7GQzxY"
}


###regenerate-refresh-token
POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI2NTc1NjcsImV4cCI6MTczMzI2MjM2N30.MAjkUOv799co5TLSQ0Bah8UqQ4CSPajvcUyLS7GQzxY"
}


###fetch-user-data
GET http://localhost:3000/user/fetch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI2NjExMDIsImV4cCI6MTczMjY2MTE2Mn0.kBOHYN1ONe9r6KRJLK3VBm_TIGRq_8wRADyd2DJSy2M



###ping
GET http://localhost:3000/api/ping
