GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI2NTUzMDIsImV4cCI6MTczMjY1NTM2Mn0.-uKoaTjY-NvPR6bT9SpmKXRA1bf_OHIm7xchxz3naZY

###ping route
GET http://localhost:3000/api/ping


###register route
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName":"Arselene",
    "lastName":"Meghlaoui",
    "username":"exodia",
    "email":"arselene.test10010@gmail.com",
    "password":"12345678"
}


###register route
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName":"Arselene",
    "lastName":"Meghlaoui",
    "username":"exodia",
    "email":"arselene.test10010@gmail.com",
    "password":"12345678"
}

###verify-credentials route
POST  http://localhost:3000/auth/validate-credentials
Content-Type: application/json

{
    "email":"arselene.test10010@gmail.com",
    "password":"12345678"
}

###verify-locations route
POST  http://localhost:3000/auth/validate-location
Content-Type: application/json

{
    "latitude":"36.815099",
    "longitude":"7.716793"
}

###verify-pins route
POST  http://localhost:3000/auth/validate-pins
Content-Type: application/json

{
    "userId":"674f1244d7b2d7888d49ff78",
    "pin1":"9222",
    "pin2":"1179"
}


###logout route
POST  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzI1NzQzMTQsImV4cCI6MTczMzE3OTExNH0.3W1mD95EYpW4WrFT3jliYmKxBU9Ud8pZCKB71Q9gtFM"
}


###check-refresh-token route
POST http://localhost:3000/auth/check-refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRmMTI0NGQ3YjJkNzg4OGQ0OWZmNzgiLCJpYXQiOjE3MzMyMzUzMzYsImV4cCI6MTczMzg0MDEzNn0.uIptsBCSY7Tg1LYpxVhte2lW6SgbpXQI1x7IYBmjsBs"
}


###regenerate-refresh-token
POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzQzYWZiYmI0MDQ0NjU4OGE4MTA2M2YiLCJpYXQiOjE3MzMyMzI3NDUsImV4cCI6MTczMzgzNzU0NX0.zdMzyOI4rEgZPH3GriHp7OuFrZIOnphfHDBi4wYufVU"
}


###fetch-user-data
GET http://localhost:3000/user/fetch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzRmMTI0NGQ3YjJkNzg4OGQ0OWZmNzgiLCJpYXQiOjE3MzMyMzUzMzYsImV4cCI6MTczMzIzODkzNn0.xDI5OK2ZvEEWZT1tSmX_6wGSczbizgbJONaGHok7Gpg
